[package]
name = "demo"
version = "5.2.0"
authors = ["NeuML"]
license = "Apache-2.0"
readme = "README.md"
description = """
txtai demo in Rust
"""
edition = "2018"

[dependencies]
txtai = { version = "5.2"}
tokio = { version = "0.2", features = ["full"] }
