[package]
name = "demo"
version = "7.3.0"
authors = ["NeuML"]
license = "Apache-2.0"
readme = "README.md"
description = """
txtai demo in Rust
"""
edition = "2018"

[dependencies]
txtai = { version = "7.3" }
tokio = { version = "1.0", features = ["full"] }
openssl-sys = { features = ["vendored"] }
