[package]
name = "demo"
version = "2.0.0"
authors = ["NeuML"]
license = "Apache-2.0"
readme = "README.md"
description = """
txtai demo in Rust
"""
edition = "2018"

[dependencies]
txtai = { path = "2.0"}
tokio = { version = "0.2", features = ["full"] }
